# Build settings
markdown: redcarpet
highlighter: pygments
exclude: [RAKEFILE, README.md, LICENCE]

# Site settings
title: "Jeroen Leenarts"
description: > # this means to ignore newlines until "email:"
   About me and my work

email: jeroen.leenarts@gmail.com
#blog logo
logo: "/assets/images/author.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Jeroen Leenarts'
author: 'Jeroen Leenarts'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blog.leenarts.net" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/leenarts
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/jeroenleenarts
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
